spring:

  datasource:
    url: jdbc:mysql://localhost:3306/athink_all?characterEncoding=UTF-8&serverTimezone=CTT
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    tomcat:
      max-active: 20
      max-idle: 10
      min-idle: 10
      initial-size: 10

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none

  thymeleaf:
    cache: false

  mail:
    #自定义的邮箱发送者
    sender: 1814125399@qq.com
    host: smtp.qq.com
#    host: 183.232.95.86:80
#    username: 813317539@qq.com
#    password: xykrwjaqxwnkbehi
    username: 1814125399@qq.com
    password: bmcofjcxitsfejbj
    protocol: smtp
    #ssl配置
    default-encoding: UTF-8
    port: 465
    test-connection: false
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
        imap:
          ssl:
            socketFactory:
              fallback: false



  jmx:
    enabled: false



